spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
server:
  #  port: 8081
  port: 8080
